name: Build self-contained binary (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          choco install python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd server
          python -m pip install -r requirements.txt

      - name: Compile with PyInstaller
        run: |
          cd server
          pyinstaller pyinstaller.spec

      - name: Zip the Executable
        run: |
          Compress-Archive -Path server/dist -DestinationPath server/dist.zip

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Build-Windows
          path: server/dist.zip
