name: Build self-contained binary (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv

      - name: Install Dependencies
        run: |
          cd server
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Compile with PyInstaller
        run: |
          cd server
          python3 -m pip install pyinstaller
          pyinstaller pyinstaller.spec

      - name: Zip the Executable
        run: |
          cd server
          zip -r dist.zip dist

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Build-Linux
          path: server/dist.zip
